#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

swift test
"$SCRIPT_DIR/build_and_run.sh" --build-sandboxed
"$SCRIPT_DIR/verify_metadata_write.sh" "${TESTSTRIP_HEADLESS_METADATA_COUNT:-100}" "${TESTSTRIP_HEADLESS_METADATA_MAX_SECONDS:-5}"
"$SCRIPT_DIR/verify_import_preview_drain.sh" "${TESTSTRIP_HEADLESS_IMPORT_COUNT:-100}" "${TESTSTRIP_HEADLESS_IMPORT_MAX_SECONDS:-5}" "${TESTSTRIP_HEADLESS_PREVIEW_DRAIN_MAX_SECONDS:-10}"
"$SCRIPT_DIR/verify_source_availability.sh" "${TESTSTRIP_HEADLESS_SOURCE_COUNT:-120}" "${TESTSTRIP_HEADLESS_SOURCE_MAX_SECONDS:-5}"
"$SCRIPT_DIR/verify_preview_render.sh" "${TESTSTRIP_HEADLESS_PREVIEW_COUNT:-12}" "${TESTSTRIP_HEADLESS_PREVIEW_MAX_SECONDS:-5}"
"$SCRIPT_DIR/verify_worker_recovery.sh" "${TESTSTRIP_HEADLESS_WORKER_RECOVERY_COUNT:-24}" "${TESTSTRIP_HEADLESS_WORKER_RECOVERY_MAX_SECONDS:-5}"
